doctrine:
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            BoltEnhancedSeo:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/vendor/brandefy-studio/bolt-enhanced-seo/src'
                prefix: 'Brandefy\BoltEnhancedSeo'
                alias: BoltEnhancedSeo

framework:
    translator:
        paths: ['%kernel.project_dir%/vendor/brandefy-studio/bolt-enhanced-seo/translations']
